config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  
  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to:'recipes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes do 
    resources :reviews 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user 
    has_many :reviews 
    has_many :users, through: :reviews 
    has_many :ingredients, dependent: :destroy
	accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

	has_many :steps, dependent: :destroy
	accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true


    has_attached_file :recipe_img, styles: { recipe_index: "250x350>", recipe_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :recipe_img, content_type: /\Aimage\/.*\z/

validates :title, presence: true
validates :description, presence: true


end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :recipe
    belongs_to :user 

    validates :comment, presence: true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
         has_many :recipes 
         has_many :reviews
         has_many :reviewed_recipes, through: :reviews, source: :recipe
         
         def self.create_from_provider_data(provider_data)
          where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
            user.email = provider_data.info.email
            user.password = Devise.friendly_token[0, 20]
          end
        end
      end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/omniauth_controller.rb
class OmniauthController < Devise::OmniauthCallbacksController
  
  def facebook
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user
      else
        flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing in later.'
        redirect_to new_user_registration_url
      end
    end
    def failure
      flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
      redirect_to new_user_registration_url
    end
  end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    def index 
        @recipes = Recipe.all.order("created_at DESC")
    end

    def show 
        if @recipe.reviews.blank?
			@average_review = 0
		else
			@average_review = @recipe.reviews.average(:rating).round(2)
		end
	end
    def new 
        @recipe = current_user.recipes.build
    end

    def create 
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.save 
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit 
    end

    def update
        if @recipe.update(recipe_params)
            redirect_to recipe_path(@recipe)
        else
            render 'edit'
        end
    end

    def destroy
        @recipe.destroy 
        redirect_to root_path
    end



    private

    def recipe_params 
        params.require(:recipe).permit(:title, :description, :recipe_img, ingredients_attributes:[:id, :content, :_destroy], steps_attributes:[:id, :direction, :_destroy])
    end

    def find_recipe 
        @recipe = Recipe.find(params[:id]) 
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_recipe
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]

    def new 
        @review = Review.new 
    end

    def create 
        @review = Review.new(review_params)
        @review.recipe_id = @recipe.id 
        @review.user_id = current_user.id 
        if @review.save 
            redirect_to recipe_path(@recipe)
        else
            render 'new'
        end
    end

    def edit 
    end


    def update 
        if @review.update(review_params)
            redirect_to recipe_path(@recipe)
        else
            render 'edit'
        end
    end


    def destroy 
        @review.destroy 
        redirect_to recipe_path(@recipe)
    end

    private 

    def review_params 
        params.require(:review).permit(:rating, :comment)
    end

    def find_recipe 
        @recipe = Recipe.find(params[:recipe_id])
    end

    def find_review 
        @review = Review.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlimerSocial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'raty', 'data-turbolinks-track': 'reload' %>



  </head>

  <body>

   <nav class="navbar navbar-default">
  <div class="container">
  <div class="navbar-header">
  <%= link_to "Slimer Social", root_path, class: "navbar-brand"%>
  </div>
  <ul class="nav navbar-nav">
  <li> <%= link_to "Sign Up", new_user_registration_path %></li>
<% if user_signed_in? %>
<li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
<% else %>
<li> <%= link_to "Log In", new_user_session_path %></li>
<% end %>



  </ul>

<ul>
<ul class="nav navbar-nav navbar-right">
<% if user_signed_in? %>
<li> <%= link_to "Add Recipe", new_recipe_path %> </li>
<% end %>
</ul>


</div>
</nav>

     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe do |f| %>
<%= f.file_field :recipe_img %>
<%= f.input :title, label: "Recipe Title" %>
<%= f.input :description %>




<h3>Add Ingredients</h3>
     <%= f.simple_fields_for :ingredients do |ingredient| %>
      <%= render 'ingredient_fields', f: ingredient %>
    <% end %>

    <div class="links">
     <%= link_to_add_association 'Add Ingredient', f, :ingredients %>
   </div>

   <h3>Add Steps</h3>
     <%= f.simple_fields_for :steps do |step| %>
      <%= render 'step_fields', f: step %>
    <% end %>
    <div class="links">
     <%= link_to_add_association 'Add Step', f, :steps %>
   </div>
   <br>
   <%= f.button :submit, class: "btn-custom2" %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
	<div class="field">
        <%= f.input :content %>

		
		<%= link_to_remove_association "Remove Ingredient", f %>
	</div><!-- field -->
</div><!-- nested fields-->

app/views/recipes/_step_fields.html.erb
<div class="nested-fields">
	<div class="field">
    <%= f.input :direction %>



		<%= link_to_remove_association "Remove Step", f %>
	</div><!-- field -->
</div><!-- nested fields-->

app/views/recipes/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<div class="edit-recipe-form">
<h1> Edit Recipe </h1>
<%= render 'form', recipe: @recipe %>



</div>
</div>

app/views/recipes/index.html.erb
<div class="containter">

<div class="row">
<div class="col-md-3">

    <% @recipes.each do |recipe| %>

<a href="/recipes/<%= recipe.id %>">
    <%= image_tag recipe.recipe_img.url(:recipe_index), class: "recipe" %></a>
    <h2> <%= link_to recipe.title, recipe_path(recipe) %></h2>
</div>
<% end %>

    </div>
</div>
</div>
</div>

app/views/recipes/new.html.erb
<div class="col-md-6 col-md-offset-3">


<div class="new-recipe-form">
<h1>New Recipe </h1>


<%= render 'form' %>

</div>
</div>

app/views/recipes/show.html.erb
<div class="row">

<div class="col-md-4">
    <%= image_tag @recipe.recipe_img.url(:recipe_show), class: "recipe-show" %>
</div>

<div class="col-md-8">
<div class="recipe-info">
    <h1 class="recipe-title"> <%= @recipe.title %> </h1>
	<h2>By: <%= @recipe.user.email %> </h2>
    <div class="average-review-rating" data-score=<%= @average_review %>></div>
    <span class="number-of-reviews"> Based on <%=@recipe.reviews.count %> reviews </span>
    <p class="recipe-desc"> <%= @recipe.description %> </p>
    <p>
  

<h3>Ingredients</h3>
<ul>
	<% for @ingredient in @recipe.ingredients %>
		<li><%= @ingredient.content %></li>

	<% end %>
</ul>

<h3>Steps</h3>
<ol>
	<% for @step in @recipe.steps %>
		<li><%= @step.direction %></li>
	<% end %>
</ol>
</div>

</div>
</div>
</div>


</div>

<div class="row">

	<div class="col-md-4">
    <div class="reviews">
<!-- Where the reviews/ratings will go -->
<h1>Reviews</h1>
    <%= render @recipe.reviews %>
        <div>
            <%= link_to "Add Review", new_recipe_review_path(@recipe), class: "btn btn-custom" %>

</div>
        </div>

    </div>	

</div>

<div class="links btn-group">

<%= link_to "Back", root_path, class: "btn btn-custom" %>


<% if user_signed_in? %>

<% if @recipe.user_id == current_user.id %>

<%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-custom"  %>
<%= link_to "Delete", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom"  %>

<% end %>
<% end %>
</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/reviews/_form.html.erb
<%= simple_form_for ([@recipe, @recipe.reviews.build]) do |f| %>
    <div id="rating-form">
    <label>Rating</label>
    </div>
    <%= f.input :comment %>
    <%= f.button :submit, class: "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">

<div class="review-rating" data-score="<%= review.rating %>"></div>
<p class="review-comment"> <%= review.comment %></p>
<p> <%= review.user.email %></p>

<% if user_signed_in? %>
    <% if review.user_id == current_user.id %>

    <div class="links btn-group">

    <%= link_to "Edit", edit_recipe_review_path(review.recipe, review), class: "btn btn-custom"%>
    <%= link_to "Delete", recipe_review_path(review.recipe, review), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-custom"  %>

</div>
    <% end %>
<% end %>

</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<div class="edit-review-form">




<h1>Edit Review </h1>
<%= simple_form_for([@recipe, @review]) do |f| %>
    <div id="rating-form">
    <label>Rating</label>
    </div>
    <%= f.input :comment %>
    <%= f.button :submit, class: "btn-custom2" %>
    <% end %>
</div>
</div>


    <script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

<div class="new-review-form">


<h1> New Review </h1>

<%= render 'form' %>

</div>
</div>